# This workflow will generate html file from json
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Site generator

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install json
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Generate site
      run: |
        if ! [ -d html ]; then mkdir html; fi
        for project in $(ls projects); do
          python site-generator.py < "$project" > html/"$project".html
        done
